---
# PLAY 1: Talks to Proxmox to build the VM
- name: Stage 1 - Clone and Configure VM
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Ensure dependencies are present
      ansible.builtin.pip:
        name: proxmoxer
        state: present

    - name: Clone Template 9000 to New VM
      community.proxmox.proxmox_kvm:
        api_user: "root@pam"
        api_password: "{{ proxmox_password }}"
        api_host: "192.168.42.141" # Use the IP from your successful test
        node: "rent"        # Or use a variable if you have a favorite node
        clone: "noble-cloud-template"
        name: "{{ user_vm_name }}"
        newid: "{{ user_vm_id }}"
        timeout: 600
        storage: "roger"
        format: qcow2
        citype: nocloud
        # Ensure your public SSH key is here so you can log in
        sshkeys: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID7mSEzQ3wuj8ktsUQuqVpchDvou5TFxqOAVfstHY9n0 awx@k3s"
        ipconfig:
          ipconfig0: "ip=dhcp"

    - name: Start the new VM
      community.proxmox.proxmox_kvm:
        api_user: "root@pam"
        api_password: "{{ proxmox_password }}"
        api_host: "192.168.42.141"
        node: "rent"
        vmid: "{{ user_vm_id }}"
        state: started

    - name: Wait for VM to boot and get IP
      ansible.builtin.pause:
        seconds: 45

    - name: Retrieve IP from Guest Agent
      ansible.builtin.shell: "qm guest network-get {{ user_vm_id }} --agent 1 | grep 'ip-address' | head -n 1 | awk '{print $4}' | cut -d/ -f1"
      register: new_vm_ip
      delegate_to: 192.168.42.147 # Use the Proxmox IP that worked
      remote_user: root
      # The Fix: Retry 10 times, waiting 10 seconds between each try
      until: new_vm_ip.stdout != ""
      retries: 10
      delay: 10

    - name: Add New VM to Temporary Inventory
      ansible.builtin.add_host:
        name: "{{ new_vm_ip.stdout }}"
        groups: "provisioned_nodes"
        ansible_user: "ubuntu"

# PLAY 2: Talks to the NEW VM to install Docker
- name: Stage 2 - Install Docker
  hosts: provisioned_nodes
  become: true
  tasks:
    - name: Run Docker Installation Script
      ansible.builtin.shell: curl -sSL https://get.docker.com | sh

    - name: Ensure Docker service is enabled
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes
