---
- name: Step 1 - Create the VM in Proxmox
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Clone the Noble Template
      community.general.proxmox_kvm:
        api_user: "root@pam"
        api_password: "{{ proxmox_password }}"
        api_host: "192.168.1.XX"
        node: "pve-01"
        clone: 9000
        name: "{{ user_vm_name }}" # This comes from the Survey
        vmid: "{{ user_vm_id }}"   # This comes from the Survey
        timeout: 500
        citype: nocloud
        sshkeys: "ssh-rsa YOUR_PUBLIC_KEY_HERE"
        ipconfig:
          ipconfig0: "ip=dhcp"

    - name: Start the VM
      community.general.proxmox_kvm:
        api_user: "root@pam"
        api_password: "{{ proxmox_password }}"
        api_host: "192.168.1.XX"
        node: "pve-01"
        vmid: "{{ user_vm_id }}"
        state: started

    - name: Wait for SSH to become available
      ansible.builtin.wait_for:
        host: "{{ user_vm_name }}"
        port: 22
        delay: 10
        timeout: 300

- name: Step 2 - Install Docker on the New VM
  hosts: "{{ user_vm_name }}"
  become: true
  tasks:
    - name: Install Docker using the official script
      ansible.builtin.shell: curl -sSL https://get.docker.com | sh

    - name: Ensure Docker is started
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes
