---
# PLAY 1: Talks to Proxmox to build the VM
- name: Stage 1 - Clone and Configure VM
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Ensure dependencies are present
      ansible.builtin.pip:
        name: proxmoxer
        state: present

    - name: Clone and Start VM
      community.proxmox.proxmox_kvm:
        api_user: "root@pam"
        api_password: "{{ proxmox_password }}"
        api_host: "192.168.42.141"
        node: "rent"
        clone: "noble-cloud-template"
        newid: "{{ user_vm_id }}"
        name: "{{ user_vm_name }}"
        ipconfig:
          ipconfig0: "ip=dhcp"
        state: started  # Clones and starts the VM

    - name: Wait for Guest Agent to report IPv4
      ansible.builtin.shell: |
        qm guest network-get {{ user_vm_id }} --agent 1 | grep -oP 'ip-address": "\K192\.168\.[0-9.]+' | head -n 1
      register: vm_ipv4
      delegate_to: 192.168.42.147
      remote_user: root
      until: vm_ipv4.stdout != ""
      retries: 20
      delay: 10

    - name: Add New VM to Inventory
      ansible.builtin.add_host:
        name: "{{ vm_ipv4.stdout }}"
        groups: "provisioned_nodes"
        ansible_user: "ubuntu"
        ansible_ssh_extra_args: "-o StrictHostKeyChecking=no" # Prevents SSH thumbprint prompt

    - name: Wait for SSH to be ready
      ansible.builtin.wait_for:
        host: "{{ vm_ipv4.stdout }}"
        port: 22
        state: started
        timeout: 120

# PLAY 2: Talks to the NEW VM to install Docker
- name: Stage 2 - Install Docker
  hosts: provisioned_nodes
  become: true
  gather_facts: true # Helpful for systemd tasks
  tasks:
    - name: Run Docker Installation Script
      ansible.builtin.shell: curl -sSL https://get.docker.com | sh
      args:
        creates: /usr/bin/docker # Skips if already installed

    - name: Ensure Docker service is enabled
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes
