---
# PLAY 1: Infrastructure Provisioning
- name: Stage 1 - Clone and Configure VM
  hosts: localhost
  gather_facts: false
  tasks:
    # ADDED THIS: Installs the required library into the AWX runner pod
    - name: Ensure proxmoxer is installed
      ansible.builtin.pip:
        name: proxmoxer
        state: present

    - name: Clone Template to New VM
      community.proxmox.proxmox_kvm:
        api_user: "root@pam"
        api_password: "{{ proxmox_password }}"
        api_host: "192.168.42.141"
        node: "rent"
        clone: "noble-cloud-template"
        newid: "{{ user_vm_id }}"
        name: "{{ user_vm_name }}"
        # --- CLOUD-INIT SETTINGS ---
        ciuser: "awx"
        sshkeys: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID7mSEzQ3wuj8ktsUQuqVpchDvou5TFxqOAVfstHY9n0 awx@k3s"
        ipconfig:
          ipconfig0: "ip=dhcp"
        # ---------------------------
        state: present
        timeout: 600

    - name: Start the newly created VM
      community.proxmox.proxmox_kvm:
        api_user: "root@pam"
        api_password: "{{ proxmox_password }}"
        api_host: "192.168.42.141"
        node: "rent"
        vmid: "{{ user_vm_id }}"
        state: started

    - name: Wait for Guest Agent to report IPv4
      ansible.builtin.shell: |
        qm guest cmd {{ user_vm_id }} network-get-interfaces | grep -oE '192\.168\.[0-9]+\.[0-9]+' | head -n 1
      register: vm_ipv4
      delegate_to: 192.168.42.147
      remote_user: root
      until: vm_ipv4.stdout != ""
      retries: 30
      delay: 10

    - name: Add New VM to Inventory
      ansible.builtin.add_host:
        name: "{{ vm_ipv4.stdout }}"
        groups: "provisioned_nodes"
        ansible_user: "awx"
        ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"

    - name: Wait for SSH to be ready
      ansible.builtin.wait_for:
        host: "{{ vm_ipv4.stdout }}"
        port: 22
        state: started
        timeout: 120

# PLAY 2: Software Provisioning
- name: Stage 2 - Install Docker
  hosts: provisioned_nodes
  become: true
  gather_facts: false # Important: don't gather facts until we're sure the user exists
  tasks:
    - name: Wait for SSH to be fully responsive for the new user
      ansible.builtin.wait_for_connection:
        delay: 5
        timeout: 120

    - name: Gather facts now that awx user is ready
      ansible.builtin.setup:
    - name: Run Docker Installation Script
      ansible.builtin.shell: curl -sSL https://get.docker.com | sh
      args:
        creates: /usr/bin/docker

    - name: Ensure Docker service is enabled
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes
