---
# PLAY 1: Talks to your Proxmox Host (Localhost or PVE Node)
- name: Step 1 - Create the VM in Proxmox
  hosts: localhost  # Or your Proxmox node group
  gather_facts: false
  tasks:
    - name: Clone the Noble Template
      community.general.proxmox_kvm:
        api_user: "root@pam"
        api_password: "{{ proxmox_password }}"
        api_host: "192.168.1.XX"
        node: "pve-01"
        clone: 9000
        name: "{{ user_vm_name }}"
        vmid: "{{ user_vm_id }}"
        timeout: 500
        citype: nocloud
        # Make sure this matches your actual SSH key
        sshkeys: "ssh-rsa YOUR_PUBLIC_KEY_HERE"
        ipconfig:
          ipconfig0: "ip=dhcp"

    - name: Start the VM
      community.general.proxmox_kvm:
        node: "pve-01"
        vmid: "{{ user_vm_id }}"
        state: started

    - name: Wait for Cloud-init to finish (30 seconds)
      ansible.builtin.pause:
        seconds: 30

    # >>> THIS IS WHERE YOUR BLOCK GOES <<<
    - name: Get the IP of the new VM
      shell: qm guest network-get {{ user_vm_id }} --agent 1 | grep "ip-address" | head -n 1 | awk '{print $4}' | cut -d/ -f1
      register: new_vm_ip

    - name: Add the new VM to the temporary inventory
      add_host:
        name: "{{ new_vm_ip.stdout }}"
        groups: "new_docker_nodes"
        ansible_ssh_user: "ubuntu" 

# PLAY 2: Talks directly to the NEW VM you just created
- name: Step 2 - Install Docker on the New VM
  hosts: new_docker_nodes  # This matches the 'groups' name above
  become: true
  tasks:
    - name: Install Docker
      ansible.builtin.shell: curl -sSL https://get.docker.com | sh
