# PLAY 1: Infrastructure Provisioning
- name: Stage 1 - Clone and Configure VM
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Ensure proxmoxer is installed
      ansible.builtin.pip:
        name: ["proxmoxer", "requests"]
        state: present

    - name: Clone Template to New VM
      community.proxmox.proxmox_kvm:
        api_user: "root@pam"
        api_password: "{{ proxmox_password }}"
        api_host: "192.168.42.141"
        node: "rent"
        clone: "noble-cloud-template" # Ensure this is now 20GB!
        newid: "{{ user_vm_id }}"
        name: "{{ user_vm_name }}"
        full: yes                    # Full independence
        storage: "roger"
        timeout: 1200
        state: present

    - name: Configure Cloud-Init for AWX user
      community.proxmox.proxmox_kvm:
        api_user: "root@pam"
        api_password: "{{ proxmox_password }}"
        api_host: "192.168.42.141"
        node: "rent"
        vmid: "{{ user_vm_id }}"
        update: yes
        ciuser: "awx"
        sshkeys: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID7mSEzQ3wuj8ktsUQuqVpchDvou5TFxqOAVfstHY9n0 awx@k3s"
        ipconfig:
          ipconfig0: "ip=dhcp"

    - name: Start the newly created VM
      community.proxmox.proxmox_kvm:
        api_user: "root@pam"
        api_password: "{{ proxmox_password }}"
        api_host: "192.168.42.141"
        vmid: "{{ user_vm_id }}"
        state: started

    - name: Wait for Guest Agent to report IPv4
      ansible.builtin.shell: |
        qm guest cmd {{ user_vm_id }} network-get-interfaces | grep -oE '192\.168\.[0-9]+\.[0-9]+' | head -n 1
      register: vm_ipv4
      delegate_to: 192.168.42.147
      remote_user: root
      until: vm_ipv4.stdout != ""
      retries: 30
      delay: 10

    - name: Add New VM to Inventory
      ansible.builtin.add_host:
        name: "{{ vm_ipv4.stdout }}"
        groups: "provisioned_nodes"
        ansible_user: "awx"
        ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"

# PLAY 2: Software Provisioning
- name: Stage 2 - Install Docker
  hosts: provisioned_nodes
  become: true
  tasks:
    - name: Wait for any background apt processes to finish
      ansible.builtin.shell: |
        while fuser /var/lib/dpkg/lock-frontend /var/lib/apt/lists/lock /var/lib/dpkg/lock >/dev/null 2>&1; do 
          sleep 5
        done
      timeout: 300

    - name: Install Docker
      ansible.builtin.apt:
        name: [docker.io, docker-compose]
        state: present
        update_cache: yes
