---
# PLAY 1: Talks to Proxmox to build the VM
- name: Stage 1 - Clone and Configure VM
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Ensure dependencies are present
      ansible.builtin.pip:
        name: proxmoxer
        state: present

---
- name: Stage 1 - Clone and Configure VM
  hosts: localhost
  gather_facts: false
  vars:
    # We assume your gateway is .1 of your subnet
    network_gw: "192.168.42.1"
  tasks:
    - name: Clone and Configure Network
      community.proxmox.proxmox_kvm:
        api_user: "root@pam"
        api_password: "{{ proxmox_password }}"
        api_host: "192.168.42.141"
        node: "rent"
        clone: "noble-cloud-template"
        newid: "{{ user_vm_id }}"
        name: "{{ user_vm_name }}"
        # This ensures the virtual NIC is properly defined
        net0: "virtio,bridge=vmbr0"
        # Dynamic IP assignment from your Survey
        ipconfig:
          ipconfig0: "ip={{ user_vm_ip }}/24,gw={{ network_gw }}"
        state: present

    - name: Start VM
      community.proxmox.proxmox_kvm:
        node: "rent"
        vmid: "{{ user_vm_id }}"
        state: started
        api_host: "192.168.42.141"
        api_user: "root@pam"
        api_password: "{{ proxmox_password }}"

    - name: Add to Inventory and Provision
      ansible.builtin.add_host:
        name: "{{ user_vm_ip }}"
        groups: "provisioned_nodes"
        ansible_user: "ubuntu"

# PLAY 2: Talks to the NEW VM to install Docker
- name: Stage 2 - Install Docker
  hosts: provisioned_nodes
  become: true
  tasks:
    - name: Run Docker Installation Script
      ansible.builtin.shell: curl -sSL https://get.docker.com | sh

    - name: Ensure Docker service is enabled
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes
