---
- name: View Containers in All Docker Networks
  hosts: docker  # Replace with your Docker host group
  collections:
    - community.docker
  gather_facts: false
  tasks:
    - name: Get all Docker network names
      community.docker.docker_network_info:
        all: yes
      register: all_networks_info

    - name: Loop through network names and get details
      community.docker.docker_network_info:
        name: "{{ network.name }}"
      register: network_details
      loop: "{{ all_networks_info.networks }}"
      loop_control:
        loop_var: network

    - name: Display containers in each network
      debug:
        msg: "Network: {{ network_details.results[item].network.Name }}"
      loop: "{{ network_details.results | length | list }}"
      loop_control:
        index_var: item

    - name: Display container details
      debug:
        msg: "  Containers: {{ network_details.results[item].network.Containers | dict2items }}"
      loop: "{{ network_details.results | length | list }}"
      loop_control:
        index_var: item
      when: network_details.results[item].network.Containers is defined and network_details.results[item].network.Containers | length > 0
