- name: Update and upgrade Docker Servers
  hosts: docker
  tasks:
    - name: Update package list
      become: yes
      apt:
        update_cache: yes

    - name: Upgrade all packages
      become: yes
      apt:
        upgrade: dist
