---
- hosts: docker
  gather_facts: false
  vars:
    docker_network: bridge gitea gotify dium dockage
  collections:
    - community.docker
  tasks:
    - name: "get network info"
      docker_network_info:
        name: "{{ docker_network }}"
      register: net_info

    - name: "get container info"
      docker_container_info:
        name: "{{ item }}"
      register: container_info
      loop: "{{ net_info.network.Containers.keys() }}"

    - debug:
        msg: "{{ item }}"
      loop: "{{ container_info.results|json_query('[].container.Name') }}"
