---
- name: View Containers in All Docker Networks
  hosts: docker  # Replace with your Docker host group
  collections:
    - community.docker
  gather_facts: false
  tasks:
    - name: Get all Docker networks
      community.docker.docker_network_info:
        all: yes
      register: docker_networks

    - name: Get details for each network and its containers
      community.docker.docker_network_info:
        name: "{{ item.name }}"
      register: network_details
      loop: "{{ docker_networks.networks }}"

    - name: Display containers in each network
      debug:
        msg: "Network: {{ item.network.Name }}"
      loop: "{{ network_details.results }}"

    - name: Display container details
      debug:
        msg: "  Containers: {{ item.network.Containers | dict2items }}"
      loop: "{{ network_details.results }}"
      when: item.network.Containers is defined and item.network.Containers | length > 0
