- name: Update and upgrade Docker Servers
  hosts: all
  become: true
  remote_user: awx
  serial: 1
  tasks:
    - name: Update package list
      become: yes
      apt:
        update_cache: yes

    - name: Upgrade all packages
      become: yes
      apt:
        upgrade: dist
