- name: Update and upgrade Docker Servers
  hosts: all
  become: yes
  tasks:
    - name: Update package list
      become: true
      apt:
        update_cache: yes

    - name: Upgrade all packages
      become: true
      apt:
        upgrade: dist
