---
- hosts: docker  # Replace with your target host
  gather_facts: false
  collections:
    - community.docker
  tasks:
    - name: Get Docker container information
      community.docker.docker_container_info:
        all: true
      register: container_info

    - name: Display container names
      debug:
        msg: "Container Name: {{ item.Name }}"
      loop: "{{ container_info.results }}"
