---
- name: View Containers in All Docker Networks
  hosts: docker  # Replace with your Docker host group
  collections:
    - community.docker
  gather_facts: true
  tasks:
    - name: Get all Docker networks
      community.docker.docker_network_info:
        all: yes
      register: all_networks

    - name: Get details for each network and its containers
      community.docker.docker_network_info:
        name: "{{ item.name }}"
      register: network_details
      loop: "{{ all_networks.networks }}"

    - name: Display containers in each network
      debug:
        msg: "Network: {{ network_details.results[loop.index].network.Name }}"
      loop: "{{ all_networks.networks }}"

    - name: Display container details
      debug:
        msg: "  Containers: {{ network_details.results[loop.index].network.Containers | dict2items }}"
      loop: "{{ all_networks.networks }}"
      when: network_details.results[loop.index].network.Containers is defined and network_details.results[loop.index].network.Containers | length > 0
