---
- name: Verify Factory Node Health
  hosts: all
  become: true
  tasks:
    - name: Check Container Status
      # Using double quotes for the shell and single quotes for the docker format
      ansible.builtin.shell: "docker ps --format '{{.Names}}: {{.Status}}'"
      register: docker_verify
      changed_when: false

    - name: Report Agent Health
      ansible.builtin.debug:
        msg: 
          - "Host: {{ inventory_hostname }}"
          - "Active Agents:"
          - "{{ docker_verify.stdout_lines }}"

    - name: Ensure Port 7007 (Dozzle) is listening
      ansible.builtin.wait_for:
        port: 7007
        state: started
        timeout: 5
