---
- name: Update and upgrade Proxmox
  hosts: all
  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

   
         
