---
- name: Update and upgrade Proxmox
  hosts: proxmox
  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Install python3-pip
      apt:
        pkg:
          - pipx
        state: present

    - name: Ignore PEP 668 because it's silly.
      ansible.builtin.file:
        path: /usr/lib/python3.11/EXTERNALLY-MANAGED
        state: absent

    - name: Install requests via pipx
      community.general.pipx:
        name: requests
        state: present

    - name: Install proxmer via pipx
      community.general.pipx:
        package: proxmer
        state: present
         