---
- name: Update and upgrade Proxmox
  hosts: proxmox
  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Install python3-pip
      ansible.builtin.yum:
        name: python3-pip
        state: present
        become: yes

    - name: Install requests module via pip
      ansible.builtin.pip
        name: requests
        state: present

    - name: Install proxmoxer module via pip
      ansible.builtin.pip:
        name: proxmoxer
        state: present

