---
- name: Update and upgrade Proxmox
  hosts: 192.168.42.6
  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

   
         
