---
- name: Update and upgrade Proxmox
  hosts: all
  become: true
  serial: 1
  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
        
    - name: Check if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Report reboot status
      ansible.builtin.debug:
        msg: "Node {{ inventory_hostname }} requires a reboot to finish updates!"
      when: reboot_required_file.stat.exists

   
         
