---
- name: Update and upgrade Proxmox
  hosts: proxmox
  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Install python3-pip
      apt:
        pkg:
          - pipx
        state: present

    - name: Install request via pip
      pipx:
        name: requests
        state: present

    - name: Install proxmer via pip
      pipx:
        name: proxmer
        state: present