---
- name: Test Proxmox API Connection
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Ensure proxmoxer is installed in the runner
      ansible.builtin.pip:
        name: proxmoxer
        state: present

    - name: Get Proxmox Node Status
      community.proxmox.proxmox_node_info:
        api_user: "root@pam"
        api_password: "{{ proxmox_password }}"
        api_host: "192.168.42.XX"
        validate_certs: false
      register: pve_nodes

    - name: Display Found Nodes
      ansible.builtin.debug:
        msg: "Success! AWX can see: {{ pve_nodes.proxmox_nodes | map(attribute='node') | list }}"
